<#
.SYNOPSIS
  Helper to run this Terraform config locally without editing provider.tf.

.DESCRIPTION
  Handles Azure sign-in context, backend initialization and plan/apply for a
  chosen environment. Supports two state modes:

    * Remote (default) - azurerm backend, requires -StateStorageAccount.
    * Local            - drops a backend_override.tf so state is kept in a
                         local terraform.tfstate file (good for experimenting).

  Override files (*_override.tf) are a documented Terraform feature: the
  backend block here replaces the azurerm backend in provider.tf for the run.

.PARAMETER Environment
  Which tfvars/subscription to target: test or prod.

.PARAMETER Action
  Terraform action to run after init: plan (default), apply or destroy.

.PARAMETER LocalState
  Use local state instead of the remote azurerm backend.

.PARAMETER StateStorageAccount
  Storage account name holding the remote state (required unless -LocalState).

.PARAMETER StateContainer
  Blob container for remote state. Default: tfstate.

.EXAMPLE
  ./run-local.ps1 -Environment test -LocalState -Action plan

.EXAMPLE
  ./run-local.ps1 -Environment test -StateStorageAccount mytfstate -Action apply
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [ValidateSet('test', 'prod')]
  [string]$Environment,

  [ValidateSet('plan', 'apply', 'destroy')]
  [string]$Action = 'plan',

  [switch]$LocalState,

  [string]$StateStorageAccount,

  [string]$StateContainer = 'tfstate'
)

$ErrorActionPreference = 'Stop'
Set-Location -Path $PSScriptRoot

# Subscription / tenant per environment (from the sample EV2 config)
$subscriptions = @{
  test = '<TEST_SUBSCRIPTION_ID>'
  prod = '<PROD_SUBSCRIPTION_ID>'
}
$subscriptionId = $subscriptions[$Environment]
$varFile = "$Environment.tfvars"

Write-Host "Environment    : $Environment"
Write-Host "Subscription   : $subscriptionId"
Write-Host "State mode     : $(if ($LocalState) { 'local' } else { 'remote (azurerm)' })"
Write-Host "Action         : $Action"

# 1. Azure context
az account set --subscription $subscriptionId | Out-Null
$env:ARM_SUBSCRIPTION_ID = $subscriptionId

# 2. State backend
$overrideFile = Join-Path $PSScriptRoot 'backend_override.tf'
if ($LocalState) {
  @"
# Auto-generated by run-local.ps1 -LocalState. Overrides the azurerm backend
# in provider.tf so state is stored locally. Do not commit.
terraform {
  backend "local" {}
}
"@ | Set-Content -Path $overrideFile -Encoding utf8
  terraform init -reconfigure
}
else {
  if (Test-Path $overrideFile) { Remove-Item $overrideFile -Force }
  if (-not $StateStorageAccount) {
    throw "Remote state requires -StateStorageAccount (or pass -LocalState)."
  }
  terraform init -reconfigure `
    -backend-config="storage_account_name=$StateStorageAccount" `
    -backend-config="container_name=$StateContainer" `
    -backend-config="key=$Environment.terraform.tfstate"
}

# 3. Run the requested action
switch ($Action) {
  'plan' { terraform plan -var-file=$varFile }
  'apply' { terraform apply -var-file=$varFile }
  'destroy' { terraform destroy -var-file=$varFile }
}
